tic;

filepath='C:\Users\pankaj singh\Desktop\Read\MatlabExp\Testing\EndpointDetection\';
fSeg='E6_R1_T1_LOG_E2_sigma_2_Segmentation_SPINES_s_2_t_0_5_b_100';
fEnd='E6_R1_T1_LOG_detectedEndPoints';

data= RAWfromMHD(fSeg,[],filepath); % segmented binary volume

newdata=RAWfromMHD(fEnd,[],filepath); % endpoints generated by the front propagation algorithm

endpoints=find(newdata==1); % the indices of the endpoints


[x,y,z]=ind2sub(size(newdata),endpoints); % converting the indices to the subscripts(x,y,z-coordinates)

num_endpoints=numel(endpoints);% number of endpoints

Length=zeros(num_endpoints);

Sum_intensity=zeros(num_endpoints);

for k=1:num_endpoints
    
    p1=[x(k),y(k),z(k)];
    
  for j=k:num_endpoints
      
      p2=[x(j),y(j),z(j)];
      
    [Length(k,j), Sum_intensity(k,j)]=LengthAndIntensity(data,p1,p2);
    
    %Length(k,j)=length_line;
    
    %Sum_intensity(k,j)=sum_alongLine;
  end
end



a=zeros(num_endpoints);
voxthres=4;% threshold on the number of voxels
maxlen=20; % radius(in terms of number of pixels) of the neighbourhood of each endpoint


for i=1:num_endpoints
    for j=1:num_endpoints
        
       %if (Length(i,j)>0 && (Length(i,j)==Sum_intensity(i,j)|| Length(i,j)==Sum_intensity(i,j)+2 ))
        if (Length(i,j)>0 && Length(i,j)< maxlen && (Length(i,j)<=Sum_intensity(i,j)+voxthres ))
           a(i,j)=1;
       end
    end
end

sim=find(a==1);
[icor,jcor]=ind2sub(size(a),sim);

ipoints=endpoints(icor);
jpoints=endpoints(jcor);

Z= zeros(size(data));

Z(ipoints)=1;

Z(jpoints)=1;

Z=uint8(Z);

WriteRAWandMHD(Z,strcat(fEnd,'_closeEndPoints'),filepath);

toc;


