function file_output =createAvizoVisualizationSegmentation(file_path,file_raw,file_segmentation)
file_output = fullfile(file_path,[file_raw '_Avizo.hx']);
fid = fopen(file_output,'w');

V = RAWfromMHD(file_raw,[],file_path);
v_size = size(V);


%%%%Check the type of data
elType = class(V);
switch elType
    case 'int16'
        elType = 'short';
    case 'uint8'
        elType = 'byte';
    case 'uint16'
        elType = 'ushort';
    case 'uint32'
        elType = 'ulong';
    case 'single'
        elType = 'float';
    case 'double'
        elType = 'double';
    case 'logical'
        elType = 'byte';
    otherwise
        outstr = sprintf('Data type unknown ("%s") - please modify WriteRAWandMHD.', elType);
        error(outstr);
end

fprintf(fid,'# Avizo Project\n');
fprintf(fid,'# Avizo\n');
fprintf(fid,'# Generated by Avizo 7.1.1\n');
fprintf(fid,'remove -all\n');
fprintf(fid,['remove "volrenGreen.col" "' file_raw '.raw" "' file_segmentation '.raw" "Isosurface" "Volume Rendering Settings" "Volume Rendering"\n']);
fprintf(fid,'# Create viewers\n');
fprintf(fid,'viewer setVertical 0\n');
fprintf(fid,'\n');
fprintf(fid,'\n');


fprintf(fid,'viewer 0 setBackgroundMode 0\n');
fprintf(fid,'viewer 0 setBackgroundColor 0 0 0\n');
fprintf(fid,'viewer 0 setBackgroundColor2 0.435294 0.45098 0.498039\n');
fprintf(fid,'viewer 0 setTransparencyType 5\n');
fprintf(fid,'viewer 0 setAutoRedraw 0\n');
fprintf(fid,'viewer 0 show\n');
fprintf(fid,'mainWindow show\n');
fprintf(fid,'\n');
fprintf(fid,'\n');


fprintf(fid,'set hideNewModules 1\n');
fprintf(fid,'[ load ${AMIRA_ROOT}/data/colormaps/volrenGreen.col ] setLabel "volrenGreen.col"\n');
fprintf(fid,'"volrenGreen.col" setIconPosition 0 0\n');
fprintf(fid,'"volrenGreen.col" setNoRemoveAll 1\n');
fprintf(fid,'"volrenGreen.col" fire\n');
fprintf(fid,'"volrenGreen.col" setMinMax 10 200\n');
fprintf(fid,'"volrenGreen.col" flags setValue 1\n');
fprintf(fid,'"volrenGreen.col" shift setMinMax -1 1\n');
fprintf(fid,'"volrenGreen.col" shift setButtons 0\n');
fprintf(fid,'"volrenGreen.col" shift setEditButton 1\n');
fprintf(fid,'"volrenGreen.col" shift setIncrement 0.133333\n');
fprintf(fid,'"volrenGreen.col" shift setValue 0\n');
fprintf(fid,'"volrenGreen.col" shift setSubMinMax -1 1\n');
fprintf(fid,'"volrenGreen.col" scale setMinMax 0 1\n');
fprintf(fid,'"volrenGreen.col" scale setButtons 0\n');
fprintf(fid,'"volrenGreen.col" scale setEditButton 1\n');
fprintf(fid,'"volrenGreen.col" scale setIncrement 0.1\n');
fprintf(fid,'"volrenGreen.col" scale setValue 1\n');
fprintf(fid,'"volrenGreen.col" scale setSubMinMax 0 1\n');
fprintf(fid,'"volrenGreen.col" fire\n');
fprintf(fid,'"volrenGreen.col" setViewerMask 65535\n');
fprintf(fid,'\n');
fprintf(fid,'\n');


fprintf(fid,'set hideNewModules 0\n');
fprintf(fid,['[ load -raw ' duplicateSlash(fullfile(file_path,file_raw)) '.raw little xfastest ' elType ' ' ...
    ' 1 ' num2string(v_size(1)) ' '  num2string(v_size(2)) ' '  num2string(v_size(3)) ' 0 '  num2string(v_size(1)-1) ...
    ' 0 '  num2string(v_size(2)-1) ' 0 ' num2string(v_size(3)-1) ' ] setLabel "' file_raw '.raw"\n']);
fprintf(fid,['"' file_raw '.raw" setIconPosition 20 10\n']);
fprintf(fid,['"' file_raw '.raw" sharedColormap setDefaultColor 0.8 0.8 0.8\n']);
fprintf(fid,['"' file_raw '.raw" sharedColormap setDefaultAlpha 0.500000\n']);
fprintf(fid,['"' file_raw '.raw" sharedColormap setLocalRange 0\n']);
fprintf(fid,['"' file_raw '.raw" sharedColormap setLocalMinMax 0.000000 1.000000\n']);
fprintf(fid,['"' file_raw '.raw" sharedColormap enableAlpha 1\n']);
fprintf(fid,['"' file_raw '.raw" sharedColormap enableAlphaToggle 0\n']);
fprintf(fid,['"' file_raw '.raw" sharedColormap setAutoAdjustRangeMode 0\n']);
fprintf(fid,['"' file_raw '.raw" fire\n']);
fprintf(fid,['"' file_raw '.raw" fire\n']);
fprintf(fid,['"' file_raw '.raw" setViewerMask 65535\n']);
fprintf(fid,'\n');
fprintf(fid,'\n');


fprintf(fid,'set hideNewModules 0\n');
fprintf(fid,['[ load -raw ' duplicateSlash(fullfile(file_path,file_segmentation)) '.raw little xfastest ' 'byte' ' ' ...
    ' 1 ' num2string(v_size(1)) ' '  num2string(v_size(2)) ' '  num2string(v_size(3)) ' 0 '  num2string(v_size(1)-1) ...
    ' 0 '  num2string(v_size(2)-1) ' 0 ' num2string(v_size(3)-1) ' ] setLabel "' file_segmentation '.raw"\n']);
fprintf(fid,['"' file_segmentation '.raw" setIconPosition 20 40\n']);
fprintf(fid,['"' file_segmentation '.raw" sharedColormap setDefaultColor 0.8 0.8 0.8\n']);
fprintf(fid,['"' file_segmentation '.raw" sharedColormap setDefaultAlpha 0.500000\n']);
fprintf(fid,['"' file_segmentation '.raw" sharedColormap setLocalRange 0\n']);
fprintf(fid,['"' file_segmentation '.raw" sharedColormap setLocalMinMax 0.000000 1.000000\n']);
fprintf(fid,['"' file_segmentation '.raw" sharedColormap enableAlpha 1\n']);
fprintf(fid,['"' file_segmentation '.raw" sharedColormap enableAlphaToggle 0\n']);
fprintf(fid,['"' file_segmentation '.raw" sharedColormap setAutoAdjustRangeMode 0\n']);
fprintf(fid,['"' file_segmentation '.raw" fire\n']);
fprintf(fid,['"' file_segmentation '.raw" fire\n']);
fprintf(fid,['"' file_segmentation '.raw" setViewerMask 65535\n']);
fprintf(fid,'\n');
fprintf(fid,'\n');


fprintf(fid,'set hideNewModules 0\n');
fprintf(fid,'create HxIsosurface "Isosurface"\n');
fprintf(fid,'"Isosurface" setIconPosition 503 55\n');
fprintf(fid,['"Isosurface" data connect "' file_segmentation '.raw"\n']);
fprintf(fid,'"Isosurface" colormap setDefaultColor 1 0.8 0.4\n');
fprintf(fid,'"Isosurface" colormap setDefaultAlpha 0.500000\n');
fprintf(fid,'"Isosurface" colormap setLocalRange 0\n');
fprintf(fid,'"Isosurface" colormap setLocalMinMax 0.000000 1.000000\n');
fprintf(fid,'"Isosurface" colormap enableAlpha 1\n');
fprintf(fid,'"Isosurface" colormap enableAlphaToggle 0\n');
fprintf(fid,'"Isosurface" colormap setAutoAdjustRangeMode 0\n');
fprintf(fid,'"Isosurface" fire\n');
fprintf(fid,'"Isosurface" drawStyle setValue 1\n');
fprintf(fid,'"Isosurface" fire\n');
fprintf(fid,'"Isosurface" drawStyle setSpecularLighting 1\n');
fprintf(fid,'"Isosurface" drawStyle setTexture 0\n');
fprintf(fid,'"Isosurface" drawStyle setAlphaMode 1\n');
fprintf(fid,'"Isosurface" drawStyle setNormalBinding 1\n');
fprintf(fid,'"Isosurface" drawStyle setSortingMode 1\n');
fprintf(fid,'"Isosurface" drawStyle setLineWidth 0.000000\n');
fprintf(fid,'"Isosurface" drawStyle setOutlineColor 0 0 0.2\n');
fprintf(fid,'"Isosurface" textureWrap setIndex 0 1\n');
fprintf(fid,'"Isosurface" cullingMode setValue 0\n');
fprintf(fid,'"Isosurface" threshold setMinMax 0 1\n');
fprintf(fid,'"Isosurface" threshold setButtons 0\n');
fprintf(fid,'"Isosurface" threshold setEditButton 1\n');
fprintf(fid,'"Isosurface" threshold setIncrement 0.1\n');
fprintf(fid,'"Isosurface" threshold setValue 0.5\n');
fprintf(fid,'"Isosurface" threshold setSubMinMax 0 1\n');
fprintf(fid,'"Isosurface" options setValue 0 1\n');
fprintf(fid,'"Isosurface" options setToggleVisible 0 1\n');
fprintf(fid,'"Isosurface" options setValue 1 0\n');
fprintf(fid,'"Isosurface" options setToggleVisible 1 1\n');
fprintf(fid,'"Isosurface" resolution setMinMax 0 -16777216 16777216\n');
fprintf(fid,'"Isosurface" resolution setValue 0 2\n');
fprintf(fid,'"Isosurface" resolution setMinMax 1 -16777216 16777216\n');
fprintf(fid,'"Isosurface" resolution setValue 1 2\n');
fprintf(fid,'"Isosurface" resolution setMinMax 2 -16777216 16777216\n');
fprintf(fid,'"Isosurface" resolution setValue 2 2\n');
fprintf(fid,'"Isosurface" numberOfCores setMinMax 1 8\n');
fprintf(fid,'"Isosurface" numberOfCores setButtons 1\n');
fprintf(fid,'"Isosurface" numberOfCores setEditButton 1\n');
fprintf(fid,'"Isosurface" numberOfCores setIncrement 1\n');
fprintf(fid,'"Isosurface" numberOfCores setValue 8\n');
fprintf(fid,'"Isosurface" numberOfCores setSubMinMax 1 8\n');
fprintf(fid,'"Isosurface" setLighting 1\n');
fprintf(fid,'"Isosurface" doIt hit\n');
fprintf(fid,'"Isosurface" fire\n');
fprintf(fid,'"Isosurface" setViewerMask 65535\n');
fprintf(fid,'"Isosurface" setShadowStyle 0\n');
fprintf(fid,'"Isosurface" setPickable 1\n');
fprintf(fid,'\n');
fprintf(fid,'\n');


fprintf(fid,'set hideNewModules 0\n');
fprintf(fid,'create HxVolumeRenderingSettings "Volume Rendering Settings"\n');
fprintf(fid,'"Volume Rendering Settings" setIconPosition 503 10\n');
fprintf(fid,['"Volume Rendering Settings" data connect "' file_raw '.raw"\n']);
fprintf(fid,'"Volume Rendering Settings" fire\n');
fprintf(fid,'"Volume Rendering Settings" advancedSettings setValue 1\n');
fprintf(fid,'"Volume Rendering Settings" interpolation setValue 0\n');
fprintf(fid,'"Volume Rendering Settings" interpolationAdvanced setValue 1\n');
fprintf(fid,'"Volume Rendering Settings" composition setValue 0\n');
fprintf(fid,'"Volume Rendering Settings" quality setValue 1\n');
fprintf(fid,'"Volume Rendering Settings" options setValue 0 0\n');
fprintf(fid,'"Volume Rendering Settings" options setToggleVisible 0 1\n');
fprintf(fid,'"Volume Rendering Settings" options setValue 1 1\n');
fprintf(fid,'"Volume Rendering Settings" options setToggleVisible 1 1\n');
fprintf(fid,'"Volume Rendering Settings" lighting setValue 1\n');
fprintf(fid,'"Volume Rendering Settings" gradient setState item 0 1 item 2 0.0001 \n');
fprintf(fid,'"Volume Rendering Settings" effects setValue 0 0\n');
fprintf(fid,'"Volume Rendering Settings" effects setToggleVisible 0 1\n');
fprintf(fid,'"Volume Rendering Settings" effects setValue 1 0\n');
fprintf(fid,'"Volume Rendering Settings" effects setToggleVisible 1 1\n');
fprintf(fid,'"Volume Rendering Settings" effects setValue 2 0\n');
fprintf(fid,'"Volume Rendering Settings" effects setToggleVisible 2 1\n');
fprintf(fid,'"Volume Rendering Settings" edgeEnhancement setState item 0 0 item 2 0.0001 \n');
fprintf(fid,'"Volume Rendering Settings" edge2D setState item 0 0 item 2 0.1 item 4 0.1 item 6 1 \n');
fprintf(fid,'"Volume Rendering Settings" boundaryOpacity setState item 0 0 item 2 2.5 item 4 2.5 \n');
fprintf(fid,'"Volume Rendering Settings" moveLowResolutionScale setMinMax 1 10\n');
fprintf(fid,'"Volume Rendering Settings" moveLowResolutionScale setButtons 1\n');
fprintf(fid,'"Volume Rendering Settings" moveLowResolutionScale setEditButton 1\n');
fprintf(fid,'"Volume Rendering Settings" moveLowResolutionScale setIncrement 1\n');
fprintf(fid,'"Volume Rendering Settings" moveLowResolutionScale setValue 3\n');
fprintf(fid,'"Volume Rendering Settings" moveLowResolutionScale setSubMinMax 1 10\n');
fprintf(fid,'"Volume Rendering Settings" numberOfSlices setMinMax 0 2000\n');
fprintf(fid,'"Volume Rendering Settings" numberOfSlices setButtons 1\n');
fprintf(fid,'"Volume Rendering Settings" numberOfSlices setEditButton 1\n');
fprintf(fid,'"Volume Rendering Settings" numberOfSlices setIncrement 1\n');
fprintf(fid,'"Volume Rendering Settings" numberOfSlices setValue 724\n');
fprintf(fid,'"Volume Rendering Settings" numberOfSlices setSubMinMax 0 2000\n');
fprintf(fid,'"Volume Rendering Settings" optimizations setValue 0 0\n');
fprintf(fid,'"Volume Rendering Settings" optimizations setToggleVisible 0 1\n');
fprintf(fid,'"Volume Rendering Settings" optimizations setValue 1 0\n');
fprintf(fid,'"Volume Rendering Settings" optimizations setToggleVisible 1 1\n');
fprintf(fid,'"Volume Rendering Settings" optimizations setValue 2 0\n');
fprintf(fid,'"Volume Rendering Settings" optimizations setToggleVisible 2 1\n');
fprintf(fid,'"Volume Rendering Settings" sliceAlignment setValue 1\n');
fprintf(fid,'"Volume Rendering Settings" projectionRefinement setMinMax 1 20\n');
fprintf(fid,'"Volume Rendering Settings" projectionRefinement setButtons 1\n');
fprintf(fid,'"Volume Rendering Settings" projectionRefinement setEditButton 1\n');
fprintf(fid,'"Volume Rendering Settings" projectionRefinement setIncrement 1\n');
fprintf(fid,'"Volume Rendering Settings" projectionRefinement setValue 3\n');
fprintf(fid,'"Volume Rendering Settings" projectionRefinement setSubMinMax 1 20\n');
fprintf(fid,'"Volume Rendering Settings" fire\n');
fprintf(fid,'"Volume Rendering Settings" setViewerMask 65535\n');
fprintf(fid,'"Volume Rendering Settings" setShadowStyle 0\n');
fprintf(fid,'"Volume Rendering Settings" setPickable 1\n');
fprintf(fid,'\n');
fprintf(fid,'\n');


fprintf(fid,'set hideNewModules 0\n');
fprintf(fid,'create HxVolumeRender2 "Volume Rendering"\n');
fprintf(fid,'"Volume Rendering" setIconPosition 503 30\n');
fprintf(fid,['"Volume Rendering" data connect "' file_raw '.raw"\n']);
fprintf(fid,'"Volume Rendering" volumeRenderingSettings connect "Volume Rendering Settings"\n');
fprintf(fid,'"Volume Rendering" fire\n');
fprintf(fid,'"Volume Rendering" colormap setDefaultColor 1 1 1\n');
fprintf(fid,'"Volume Rendering" colormap setDefaultAlpha 0.500000\n');
fprintf(fid,'"Volume Rendering" colormap setLocalRange 1\n');
fprintf(fid,['"Volume Rendering" colormap setLocalMinMax ' num2str(min(V(:)) + (max(V(:))-min(V(:)))/10) ' ' num2str(round(max(V(:)/3))) '\n']);
fprintf(fid,'"Volume Rendering" colormap enableAlpha 1\n');
fprintf(fid,'"Volume Rendering" colormap enableAlphaToggle 0\n');
fprintf(fid,'"Volume Rendering" colormap setAutoAdjustRangeMode 1\n');
fprintf(fid,'"Volume Rendering" colormap connect "volrenGreen.col"\n');
fprintf(fid,'"Volume Rendering" fire\n');
fprintf(fid,'"Volume Rendering" colormapLookup setValue 2\n');
fprintf(fid,'"Volume Rendering" gamma setMinMax 0.100000001490116 8\n');
fprintf(fid,'"Volume Rendering" gamma setButtons 0\n');
fprintf(fid,'"Volume Rendering" gamma setEditButton 1\n');
fprintf(fid,'"Volume Rendering" gamma setIncrement 0.526667\n');
fprintf(fid,'"Volume Rendering" gamma setValue 3\n');
fprintf(fid,'"Volume Rendering" gamma setSubMinMax 0.100000001490116 8\n');
fprintf(fid,'"Volume Rendering" alphaScale setMinMax 0 1\n');
fprintf(fid,'"Volume Rendering" alphaScale setButtons 0\n');
fprintf(fid,'"Volume Rendering" alphaScale setEditButton 1\n');
fprintf(fid,'"Volume Rendering" alphaScale setIncrement 0.1\n');
fprintf(fid,'"Volume Rendering" alphaScale setValue 1\n');
fprintf(fid,'"Volume Rendering" alphaScale setSubMinMax 0 1\n');
fprintf(fid,'"Volume Rendering" channelSelector setValue 0 1\n');
fprintf(fid,'"Volume Rendering" channelSelector setToggleVisible 0 1\n');
fprintf(fid,'"Volume Rendering" fire\n');
fprintf(fid,'"Volume Rendering" setViewerMask 65535\n');
fprintf(fid,'"Volume Rendering" select\n');
fprintf(fid,'"Volume Rendering" setPickable 1\n');
fprintf(fid,'\n');
fprintf(fid,'\n');


fprintf(fid,'set hideNewModules 0\n');
fprintf(fid,'\n');
fprintf(fid,'\n');


fprintf(fid,'viewer 0 setCameraOrientation 1 0 0 3.14159\n');
fprintf(fid,'viewer 0 setCameraPosition 255.5 255.5 -549.141\n');
fprintf(fid,'viewer 0 setCameraFocalDistance 557.391\n');
fprintf(fid,'viewer 0 setCameraNearDistance 548\n');
fprintf(fid,'viewer 0 setCameraFarDistance 618\n');
fprintf(fid,'viewer 0 setCameraType perspective\n');
fprintf(fid,'viewer 0 setCameraHeightAngle 44.9023\n');
fprintf(fid,'viewer 0 setAutoRedraw 1\n');
fprintf(fid,'viewer 0 redraw\n');
fprintf(fid,'\n');
fprintf(fid,'\n');

fprintf(fid,'theObjectPool setSelectionOrder {Volume Rendering}\n');

end

function file_out=duplicateSlash(file_path)
file_out = [];
for i =1:length(file_path)
    file_out = [file_out file_path(i)];
    if file_path(i) == '\'
        file_out(end) = '/';
    end
end

end